apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-techdocs-module-addons-contrib
  namespace: rhdh
  title: "TechDocs Add-ons Contrib"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-techdocs-module-addons-contrib
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-techdocs-module-addons-contrib
  tags: []
spec:
  packageName: "@backstage/plugin-techdocs-module-addons-contrib"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
  version: 1.1.27
  backstage:
    role: frontend-plugin-module
    supportedVersions: 1.42.5
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - contrib-techdocs-addons
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-techdocs-module-addons-contrib:
              techdocsAddons:
                - importName: ReportIssue
    - title: ReportIssue configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-techdocs-module-addons-contrib:
              techdocsAddons:
                - importName: ReportIssue
    - title: TextSize configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-techdocs-module-addons-contrib:
              techdocsAddons:
                - importName: TextSize
    - title: LightBox configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-techdocs-module-addons-contrib:
              techdocsAddons:
                - importName: LightBox
    - title: All add-ons enabled configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-techdocs-module-addons-contrib:
              techdocsAddons:
                - importName: ReportIssue
                - importName: TextSize
                - importName: LightBox
