apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-nexus-repository-manager
  namespace: rhdh
  title: "Nexus Repository Manager"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager
  tags: []
spec:
  packageName: "@backstage-community/plugin-nexus-repository-manager"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-nexus-repository-manager
  version: 1.16.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.42.5
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - nexus-repository-manager
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-nexus-repository-manager:
              mountPoints:
                - mountPoint: entity.page.image-registry/cards
                  importName: NexusRepositoryManagerPage
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      anyOf:
                        - isNexusRepositoryManagerAvailable
