apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-catalog-backend-module-gitlab
  namespace: rhdh
  title: "Catalog Backend Module GitLab"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic
  tags:
    - software-catalog
spec:
  packageName: "@backstage/plugin-catalog-backend-module-gitlab"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic
  version: 0.7.2
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.42.5
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - gitlab-catalog-integration
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            gitlab: {}
