apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-catalog-backend-module-pingidentity
  namespace: rhdh
  title: "Catalog Backend Module PingIdentity"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic
  tags:
    - software-catalog
spec:
  packageName: "@backstage-community/plugin-catalog-backend-module-pingidentity"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic
  version: 0.7.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.42.5
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - pingidentity
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            pingIdentityOrg: {}
