apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-github-issues
  namespace: rhdh
  title: "GitHub Issues"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-github-issues
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-github-issues
  tags: []
spec:
  packageName: "@backstage-community/plugin-github-issues"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-github-issues
  version: 0.13.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.42.5
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - github-issues
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-github-issues:
              mountPoints:
                - mountPoint: entity.page.issues/cards
                  importName: GithubIssuesCard
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - hasAnnotation: github.com/project-slug
