apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-catalog-backend-module-msgraph
  namespace: rhdh
  title: "@backstage/plugin-catalog-backend-module-msgraph"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic
  tags: []
spec:
  packageName: "@backstage/plugin-catalog-backend-module-msgraph"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-msgraph-dynamic
  version: 0.6.7
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.36.1
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - backstage-msgraph-catalog-module
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            microsoftGraphOrg: {}
