apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-dynamic-home-page
  namespace: rhdh
  title: "Dynamic Home Page"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-dynamic-home-page"
  dynamicArtifact: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-dynamic-home-page
  version: 1.9.2
  backstage:
    role: frontend-plugin
    supportedVersions: 1.42.5
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - home-page
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-dynamic-home-page:
              dynamicRoutes:
                - path: /
                  importName: DynamicHomePage
              mountPoints:
                - mountPoint: application/listener
                  importName: VisitListener
                - mountPoint: home.page/cards
                  importName: SearchBar
                  config:
                    layouts:
                      xl:
                        w: 10
                        h: 1
                        x: 1
                      lg:
                        w: 10
                        h: 1
                        x: 1
                      md:
                        w: 10
                        h: 1
                        x: 1
                      sm:
                        w: 10
                        h: 1
                        x: 1
                      xs:
                        w: 12
                        h: 1
                      xxs:
                        w: 12
                        h: 1
                - mountPoint: home.page/cards
                  importName: QuickAccessCard
                  config:
                    layouts:
                      xl:
                        w: 7
                        h: 8
                      lg:
                        w: 7
                        h: 8
                      md:
                        w: 7
                        h: 8
                      sm:
                        w: 12
                        h: 8
                      xs:
                        w: 12
                        h: 8
                      xxs:
                        w: 12
                        h: 8
                - mountPoint: home.page/cards
                  importName: CatalogStarredEntitiesCard
                  config:
                    layouts:
                      xl:
                        w: 5
                        h: 4
                        x: 7
                      lg:
                        w: 5
                        h: 4
                        x: 7
                      md:
                        w: 5
                        h: 4
                        x: 7
                      sm:
                        w: 12
                        h: 4
                      xs:
                        w: 12
                        h: 4
                      xxs:
                        w: 12
                        h: 4
