apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-global-floating-action-b
  namespace: rhdh
  title: "@red-hat-developer-hub/backstage-plugin-global-floating-action-button"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-global-floating-action-button"
  dynamicArtifact: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-floating-action-button
  version: 1.1.4
  backstage:
    role: frontend-plugin
    supportedVersions: 1.36.1
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - red-hat-developer-hub-backstage-plugin-global-floating-action-button
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-global-floating-action-button:
              mountPoints:
                - mountPoint: application/listener
                  importName: DynamicGlobalFloatingActionButton
