apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-backstage-plugin-datadog
  namespace: rhdh
  title: "Datadog"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog
  tags: []
spec:
  packageName: "@roadiehq/backstage-plugin-datadog"
  dynamicArtifact: ./dynamic-plugins/dist/roadiehq-backstage-plugin-datadog
  version: 2.5.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.42.5
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - datadog
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            roadiehq.backstage-plugin-datadog:
              mountPoints:
                - mountPoint: entity.page.monitoring/cards
                  importName: EntityDatadogContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isDatadogAvailable
