kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha5
metadata:
  name: rhdh
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            containers:
              - name: backstage-backend
                image: "$IMAGE_REGISTRY/$IMAGE_REPO:$TAG_NAME"
            initContainers:
              - name: install-dynamic-plugins
                image: "$IMAGE_REGISTRY/$IMAGE_REPO:$TAG_NAME"
            volumes:
              - name: dynamic-plugins-root
                ephemeral:
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 5Gi
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
      secrets:
        - name: postgres-crt
          key: postgres-crt.pem
    extraEnvs:
      secrets:
        - name: postgres-cred
    route:
      enabled: true
  database:
    enableLocalDb: false
